### ISSUE TITLE
trigger event when clicking close button after editing

### ISSUE THREAD

**Issue by ralphievolt** [manojsinghnegiwd/simple-react-editable#1]
How can i get the trigger event when i click the close button after editing?

This is how I use the component in my table row.

`<td>
      <SimpleReactEditable content={ part.description } />
    <td>`

**Comment by manojsinghnegiwd** [comment]
Hello @ralphievolt .. it is not possible for now .. cause i didn't provide any event on onClose ... but I will implement it as soon as I get home ... :smile: Thanks for suggestion.

**Comment by manojsinghnegiwd** [comment]
Hello @ralphievolt I added 2 new events `onEditingClose` and `onEditingOpen` , you can use them with your code like this.

you have to reinstall the component

``` sh
npm install simple-react-editable --save
```

``` html
<td>
     <SimpleReactEditable onEditingClose={ this.yourFunction }
     onEditingOpen={ this.yourSecondFunction } content={ part.description } />
<td>
```

For your issue the answer is onEditingClose get called whenever you close editor .. :smile: hope it helps .. and if you are finding it useful :star:  `simple-react-editable` on github

**Comment by ralphievolt** [comment]
Thanks @manojsinghnegiwd.. that was fast

**Comment by manojsinghnegiwd** [comment]
No problem @ralphievolt .. if you have any more suggestion let me know :smile:

**Comment by ralphievolt** [comment]
Hi @manojsinghnegiwd , got another problem.

I want to get the current value of my data when I click the table cell but can't get it..

`<SimpleReactEditable onEditingOpen={this._onClick.bind()}  onEditingClose={this._newDescription.bind()} content={part.description} />
`

```
 _onClick(event) {
        console.log(event.target.value);
    }
```

but it will return `undefined`.. i am not sure what i'm missing here.. it may not be related to your package 
but on my code =)

hope you can help. thanks

**Comment by ralphievolt** [comment]
I think I solved it by declaring this as
`this._newDescription = this._newDescription.bind(this);`

in my constructor.

my function
`_newDescription(event) {
       console.log(event.target.value)
    }`

`<SimpleReactEditable onEditingClose={ this._newDescription } content={part.description} />`

but on `onEditingOpen={ this._onClick }` still undefined.. i guess this suffice for now.

**Comment by manojsinghnegiwd** [comment]
Hey @ralphievolt right now I provide an event to onEditingOpen and onEditingClose .. it is not related to your code .. I will fix it when I will get home ... when fixed you will be able to get value of textarea .. :smile:

**Comment by manojsinghnegiwd** [comment]
Hey @ralphievolt I fixed the issue now you can get value of text area like this in both events

you have to reinstall the component

``` sh
npm install simple-react-editable --save
```

``` html
<SimpleReactComponent onEditingClose={ (e, value) => { console.log('editing stopped', value) }}  onEditingOpen={ (e, value) => { console.log('editing started', value) }} content="hello this thing is editable" />
```

**Comment by ralphievolt** [comment]
@manojsinghnegiwd i confirm. this works on both ways....
